//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coinpayments.Api {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class CoinpaymentsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CoinpaymentsSettings defaultInstance = ((CoinpaymentsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CoinpaymentsSettings())));
        
        public static CoinpaymentsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6a466b85e7d587e84646bfb7781f66f80ccf30505b5e5c10553f63521fc15c3f")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2dbC037f1Bbc8BD69F923c7859cB6f3fA7A510B8E92bdafA1450f5e4d7421908")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f7XVkifq9TET")]
        public string IpnSecret {
            get {
                return ((string)(this["IpnSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7532c4bb09b896972596751de2f11515")]
        public string MerchantId {
            get {
                return ((string)(this["MerchantId"]));
            }
        }
    }
}
