//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coinpayments.Api {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class CoinpaymentsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CoinpaymentsSettings defaultInstance = ((CoinpaymentsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CoinpaymentsSettings())));
        
        public static CoinpaymentsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7e52d3de2ab61dc6fa62d3bdf39f8dc2419e1de8a92c213d93fcd048cb429fa1")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48CCD816f5808Bb0ee80b4975fda41f0eEcCED81dbaA2AC5085DF9b6395dc7a6")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eKHaNscBIkXDm3szbXDvIVq1XvzIX6")]
        public string IpnSecret {
            get {
                return ((string)(this["IpnSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0ba85efeaa35d18186d58ea995f02a08")]
        public string MerchantId {
            get {
                return ((string)(this["MerchantId"]));
            }
        }
    }
}
